# Generated by Django 5.0.2 on 2024-11-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loaders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalesrecord',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
