# Generated by Django 5.0.2 on 2024-11-22 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loaders', '0007_alter_seller_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='email',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='name',
        ),
        migrations.AlterField(
            model_name='seller',
            name='address',
            field=models.CharField(default='Default Address', max_length=255),
        ),
        migrations.AlterField(
            model_name='seller',
            name='bio',
            field=models.TextField(blank=True, default='No bio provided.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone_number',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seller',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_profile.jpg', upload_to='profile_pics/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seller',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Tractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=200)),
                ('hours_used', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('specifications', models.JSONField()),
                ('image', models.ImageField(upload_to='tractor_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loaders.seller')),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loaders.tractor')),
            ],
        ),
        migrations.DeleteModel(
            name='TractorListing',
        ),
    ]
