# Generated by Django 5.0.2 on 2024-11-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loaders', '0012_order_customer_email_productview'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/default.png', upload_to='profile_pictures/'),
        ),
    ]
