# Generated by Django 5.0.2 on 2024-11-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loaders', '0013_seller_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='profile_picture',
            field=models.ImageField(default='images/default.png', upload_to='static/images'),
        ),
    ]
